name: Playwright Tests

on:
  push:
    branches: [ main ]   # run on push to main
  pull_request:
    branches: [ main ]   # also run on PRs to main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18   # same Node.js you use locally
          cache: 'npm'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # 5. Run tests
      - name: Run Playwright tests
        run: npx playwright test

      # 6. Upload HTML report (optional but useful)
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7
